# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/pgarcia/Documents/_priv/dev/atari/atari800-src/fujisan

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/pgarcia/Documents/_priv/dev/atari/atari800-src/fujisan

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/pgarcia/Documents/_priv/dev/atari/atari800-src/fujisan/CMakeFiles /Users/pgarcia/Documents/_priv/dev/atari/atari800-src/fujisan//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/pgarcia/Documents/_priv/dev/atari/atari800-src/fujisan/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Fujisan

# Build rule for target.
Fujisan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Fujisan
.PHONY : Fujisan

# fast build rule for target.
Fujisan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/build
.PHONY : Fujisan/fast

#=============================================================================
# Target rules for targets named Fujisan_autogen_timestamp_deps

# Build rule for target.
Fujisan_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Fujisan_autogen_timestamp_deps
.PHONY : Fujisan_autogen_timestamp_deps

# fast build rule for target.
Fujisan_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan_autogen_timestamp_deps.dir/build.make CMakeFiles/Fujisan_autogen_timestamp_deps.dir/build
.PHONY : Fujisan_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named Fujisan_autogen

# Build rule for target.
Fujisan_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Fujisan_autogen
.PHONY : Fujisan_autogen

# fast build rule for target.
Fujisan_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan_autogen.dir/build.make CMakeFiles/Fujisan_autogen.dir/build
.PHONY : Fujisan_autogen/fast

Fujisan_autogen/mocs_compilation.o: Fujisan_autogen/mocs_compilation.cpp.o
.PHONY : Fujisan_autogen/mocs_compilation.o

# target to build an object file
Fujisan_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/Fujisan_autogen/mocs_compilation.cpp.o
.PHONY : Fujisan_autogen/mocs_compilation.cpp.o

Fujisan_autogen/mocs_compilation.i: Fujisan_autogen/mocs_compilation.cpp.i
.PHONY : Fujisan_autogen/mocs_compilation.i

# target to preprocess a source file
Fujisan_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/Fujisan_autogen/mocs_compilation.cpp.i
.PHONY : Fujisan_autogen/mocs_compilation.cpp.i

Fujisan_autogen/mocs_compilation.s: Fujisan_autogen/mocs_compilation.cpp.s
.PHONY : Fujisan_autogen/mocs_compilation.s

# target to generate assembly for a file
Fujisan_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/Fujisan_autogen/mocs_compilation.cpp.s
.PHONY : Fujisan_autogen/mocs_compilation.cpp.s

src/atariemulator.o: src/atariemulator.cpp.o
.PHONY : src/atariemulator.o

# target to build an object file
src/atariemulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/atariemulator.cpp.o
.PHONY : src/atariemulator.cpp.o

src/atariemulator.i: src/atariemulator.cpp.i
.PHONY : src/atariemulator.i

# target to preprocess a source file
src/atariemulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/atariemulator.cpp.i
.PHONY : src/atariemulator.cpp.i

src/atariemulator.s: src/atariemulator.cpp.s
.PHONY : src/atariemulator.s

# target to generate assembly for a file
src/atariemulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/atariemulator.cpp.s
.PHONY : src/atariemulator.cpp.s

src/cartridgewidget.o: src/cartridgewidget.cpp.o
.PHONY : src/cartridgewidget.o

# target to build an object file
src/cartridgewidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/cartridgewidget.cpp.o
.PHONY : src/cartridgewidget.cpp.o

src/cartridgewidget.i: src/cartridgewidget.cpp.i
.PHONY : src/cartridgewidget.i

# target to preprocess a source file
src/cartridgewidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/cartridgewidget.cpp.i
.PHONY : src/cartridgewidget.cpp.i

src/cartridgewidget.s: src/cartridgewidget.cpp.s
.PHONY : src/cartridgewidget.s

# target to generate assembly for a file
src/cartridgewidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/cartridgewidget.cpp.s
.PHONY : src/cartridgewidget.cpp.s

src/cassettewidget.o: src/cassettewidget.cpp.o
.PHONY : src/cassettewidget.o

# target to build an object file
src/cassettewidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/cassettewidget.cpp.o
.PHONY : src/cassettewidget.cpp.o

src/cassettewidget.i: src/cassettewidget.cpp.i
.PHONY : src/cassettewidget.i

# target to preprocess a source file
src/cassettewidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/cassettewidget.cpp.i
.PHONY : src/cassettewidget.cpp.i

src/cassettewidget.s: src/cassettewidget.cpp.s
.PHONY : src/cassettewidget.s

# target to generate assembly for a file
src/cassettewidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/cassettewidget.cpp.s
.PHONY : src/cassettewidget.cpp.s

src/configurationprofile.o: src/configurationprofile.cpp.o
.PHONY : src/configurationprofile.o

# target to build an object file
src/configurationprofile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/configurationprofile.cpp.o
.PHONY : src/configurationprofile.cpp.o

src/configurationprofile.i: src/configurationprofile.cpp.i
.PHONY : src/configurationprofile.i

# target to preprocess a source file
src/configurationprofile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/configurationprofile.cpp.i
.PHONY : src/configurationprofile.cpp.i

src/configurationprofile.s: src/configurationprofile.cpp.s
.PHONY : src/configurationprofile.s

# target to generate assembly for a file
src/configurationprofile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/configurationprofile.cpp.s
.PHONY : src/configurationprofile.cpp.s

src/configurationprofilemanager.o: src/configurationprofilemanager.cpp.o
.PHONY : src/configurationprofilemanager.o

# target to build an object file
src/configurationprofilemanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/configurationprofilemanager.cpp.o
.PHONY : src/configurationprofilemanager.cpp.o

src/configurationprofilemanager.i: src/configurationprofilemanager.cpp.i
.PHONY : src/configurationprofilemanager.i

# target to preprocess a source file
src/configurationprofilemanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/configurationprofilemanager.cpp.i
.PHONY : src/configurationprofilemanager.cpp.i

src/configurationprofilemanager.s: src/configurationprofilemanager.cpp.s
.PHONY : src/configurationprofilemanager.s

# target to generate assembly for a file
src/configurationprofilemanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/configurationprofilemanager.cpp.s
.PHONY : src/configurationprofilemanager.cpp.s

src/debuggerwidget.o: src/debuggerwidget.cpp.o
.PHONY : src/debuggerwidget.o

# target to build an object file
src/debuggerwidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/debuggerwidget.cpp.o
.PHONY : src/debuggerwidget.cpp.o

src/debuggerwidget.i: src/debuggerwidget.cpp.i
.PHONY : src/debuggerwidget.i

# target to preprocess a source file
src/debuggerwidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/debuggerwidget.cpp.i
.PHONY : src/debuggerwidget.cpp.i

src/debuggerwidget.s: src/debuggerwidget.cpp.s
.PHONY : src/debuggerwidget.s

# target to generate assembly for a file
src/debuggerwidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/debuggerwidget.cpp.s
.PHONY : src/debuggerwidget.cpp.s

src/diskdrawerwidget.o: src/diskdrawerwidget.cpp.o
.PHONY : src/diskdrawerwidget.o

# target to build an object file
src/diskdrawerwidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/diskdrawerwidget.cpp.o
.PHONY : src/diskdrawerwidget.cpp.o

src/diskdrawerwidget.i: src/diskdrawerwidget.cpp.i
.PHONY : src/diskdrawerwidget.i

# target to preprocess a source file
src/diskdrawerwidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/diskdrawerwidget.cpp.i
.PHONY : src/diskdrawerwidget.cpp.i

src/diskdrawerwidget.s: src/diskdrawerwidget.cpp.s
.PHONY : src/diskdrawerwidget.s

# target to generate assembly for a file
src/diskdrawerwidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/diskdrawerwidget.cpp.s
.PHONY : src/diskdrawerwidget.cpp.s

src/diskdrivewidget.o: src/diskdrivewidget.cpp.o
.PHONY : src/diskdrivewidget.o

# target to build an object file
src/diskdrivewidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/diskdrivewidget.cpp.o
.PHONY : src/diskdrivewidget.cpp.o

src/diskdrivewidget.i: src/diskdrivewidget.cpp.i
.PHONY : src/diskdrivewidget.i

# target to preprocess a source file
src/diskdrivewidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/diskdrivewidget.cpp.i
.PHONY : src/diskdrivewidget.cpp.i

src/diskdrivewidget.s: src/diskdrivewidget.cpp.s
.PHONY : src/diskdrivewidget.s

# target to generate assembly for a file
src/diskdrivewidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/diskdrivewidget.cpp.s
.PHONY : src/diskdrivewidget.cpp.s

src/emulatorwidget.o: src/emulatorwidget.cpp.o
.PHONY : src/emulatorwidget.o

# target to build an object file
src/emulatorwidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/emulatorwidget.cpp.o
.PHONY : src/emulatorwidget.cpp.o

src/emulatorwidget.i: src/emulatorwidget.cpp.i
.PHONY : src/emulatorwidget.i

# target to preprocess a source file
src/emulatorwidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/emulatorwidget.cpp.i
.PHONY : src/emulatorwidget.cpp.i

src/emulatorwidget.s: src/emulatorwidget.cpp.s
.PHONY : src/emulatorwidget.s

# target to generate assembly for a file
src/emulatorwidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/emulatorwidget.cpp.s
.PHONY : src/emulatorwidget.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mainwindow.o: src/mainwindow.cpp.o
.PHONY : src/mainwindow.o

# target to build an object file
src/mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/mainwindow.cpp.o
.PHONY : src/mainwindow.cpp.o

src/mainwindow.i: src/mainwindow.cpp.i
.PHONY : src/mainwindow.i

# target to preprocess a source file
src/mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/mainwindow.cpp.i
.PHONY : src/mainwindow.cpp.i

src/mainwindow.s: src/mainwindow.cpp.s
.PHONY : src/mainwindow.s

# target to generate assembly for a file
src/mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/mainwindow.cpp.s
.PHONY : src/mainwindow.cpp.s

src/mediaperipheralsdock.o: src/mediaperipheralsdock.cpp.o
.PHONY : src/mediaperipheralsdock.o

# target to build an object file
src/mediaperipheralsdock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/mediaperipheralsdock.cpp.o
.PHONY : src/mediaperipheralsdock.cpp.o

src/mediaperipheralsdock.i: src/mediaperipheralsdock.cpp.i
.PHONY : src/mediaperipheralsdock.i

# target to preprocess a source file
src/mediaperipheralsdock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/mediaperipheralsdock.cpp.i
.PHONY : src/mediaperipheralsdock.cpp.i

src/mediaperipheralsdock.s: src/mediaperipheralsdock.cpp.s
.PHONY : src/mediaperipheralsdock.s

# target to generate assembly for a file
src/mediaperipheralsdock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/mediaperipheralsdock.cpp.s
.PHONY : src/mediaperipheralsdock.cpp.s

src/profileselectionwidget.o: src/profileselectionwidget.cpp.o
.PHONY : src/profileselectionwidget.o

# target to build an object file
src/profileselectionwidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/profileselectionwidget.cpp.o
.PHONY : src/profileselectionwidget.cpp.o

src/profileselectionwidget.i: src/profileselectionwidget.cpp.i
.PHONY : src/profileselectionwidget.i

# target to preprocess a source file
src/profileselectionwidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/profileselectionwidget.cpp.i
.PHONY : src/profileselectionwidget.cpp.i

src/profileselectionwidget.s: src/profileselectionwidget.cpp.s
.PHONY : src/profileselectionwidget.s

# target to generate assembly for a file
src/profileselectionwidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/profileselectionwidget.cpp.s
.PHONY : src/profileselectionwidget.cpp.s

src/settingsdialog.o: src/settingsdialog.cpp.o
.PHONY : src/settingsdialog.o

# target to build an object file
src/settingsdialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/settingsdialog.cpp.o
.PHONY : src/settingsdialog.cpp.o

src/settingsdialog.i: src/settingsdialog.cpp.i
.PHONY : src/settingsdialog.i

# target to preprocess a source file
src/settingsdialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/settingsdialog.cpp.i
.PHONY : src/settingsdialog.cpp.i

src/settingsdialog.s: src/settingsdialog.cpp.s
.PHONY : src/settingsdialog.s

# target to generate assembly for a file
src/settingsdialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/settingsdialog.cpp.s
.PHONY : src/settingsdialog.cpp.s

src/toggleswitch.o: src/toggleswitch.cpp.o
.PHONY : src/toggleswitch.o

# target to build an object file
src/toggleswitch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/toggleswitch.cpp.o
.PHONY : src/toggleswitch.cpp.o

src/toggleswitch.i: src/toggleswitch.cpp.i
.PHONY : src/toggleswitch.i

# target to preprocess a source file
src/toggleswitch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/toggleswitch.cpp.i
.PHONY : src/toggleswitch.cpp.i

src/toggleswitch.s: src/toggleswitch.cpp.s
.PHONY : src/toggleswitch.s

# target to generate assembly for a file
src/toggleswitch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Fujisan.dir/build.make CMakeFiles/Fujisan.dir/src/toggleswitch.cpp.s
.PHONY : src/toggleswitch.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Fujisan_autogen"
	@echo "... Fujisan_autogen_timestamp_deps"
	@echo "... Fujisan"
	@echo "... Fujisan_autogen/mocs_compilation.o"
	@echo "... Fujisan_autogen/mocs_compilation.i"
	@echo "... Fujisan_autogen/mocs_compilation.s"
	@echo "... src/atariemulator.o"
	@echo "... src/atariemulator.i"
	@echo "... src/atariemulator.s"
	@echo "... src/cartridgewidget.o"
	@echo "... src/cartridgewidget.i"
	@echo "... src/cartridgewidget.s"
	@echo "... src/cassettewidget.o"
	@echo "... src/cassettewidget.i"
	@echo "... src/cassettewidget.s"
	@echo "... src/configurationprofile.o"
	@echo "... src/configurationprofile.i"
	@echo "... src/configurationprofile.s"
	@echo "... src/configurationprofilemanager.o"
	@echo "... src/configurationprofilemanager.i"
	@echo "... src/configurationprofilemanager.s"
	@echo "... src/debuggerwidget.o"
	@echo "... src/debuggerwidget.i"
	@echo "... src/debuggerwidget.s"
	@echo "... src/diskdrawerwidget.o"
	@echo "... src/diskdrawerwidget.i"
	@echo "... src/diskdrawerwidget.s"
	@echo "... src/diskdrivewidget.o"
	@echo "... src/diskdrivewidget.i"
	@echo "... src/diskdrivewidget.s"
	@echo "... src/emulatorwidget.o"
	@echo "... src/emulatorwidget.i"
	@echo "... src/emulatorwidget.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mainwindow.o"
	@echo "... src/mainwindow.i"
	@echo "... src/mainwindow.s"
	@echo "... src/mediaperipheralsdock.o"
	@echo "... src/mediaperipheralsdock.i"
	@echo "... src/mediaperipheralsdock.s"
	@echo "... src/profileselectionwidget.o"
	@echo "... src/profileselectionwidget.i"
	@echo "... src/profileselectionwidget.s"
	@echo "... src/settingsdialog.o"
	@echo "... src/settingsdialog.i"
	@echo "... src/settingsdialog.s"
	@echo "... src/toggleswitch.o"
	@echo "... src/toggleswitch.i"
	@echo "... src/toggleswitch.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

